### ISSUE TITLE
View in widget 8 freezes after changing mode in melcloud

### ISSUE THREAD

**Issue by hadavid2482** [Black-Thunder/ioBroker.melcloud#109]
Hi! 

First of all -> thanks for that really good work! 
I'm facing a problem with your melcloud adapter. When changing mode in melcloud adapter, my view in widget 8 freezes in my vis. It's not just if i push a button in my vis for changing the mode - also if i change the mode external with the melcloud app, the widget freezes and it's not just at one endpoint. All endpoint acting like this. Everythin i can do, if my widget 8 freezes -> refresh the whole vis.
I'm wondering that i'm the first one who facing that problem.

Please help with that problem.

Thank you so much

**Comment by Black-Thunder** [comment]
This seems to be a problem with VIS itself and not the adapter as this also happens when you update the mode via the official app.
Also I don't use VIS, so I don't know what's happening there. Maybe check the configuration of your widget again?

**Comment by hadavid2482** [comment]
To clarify, i have a button in my VIS that control the mode and also showing the actual mode. If i dont include the button in my VIS and change externally the mode, the VIS wont freeze. But if include the button with viewing actual mode and changing externally, the VIS freezes. From my perspective it's something in the "view in widget 8" or the melcloud adapter.

**Comment by Black-Thunder** [comment]
As the adapter doesn't provide any visualization it has to be either a misconfigured widget or a general problem in VIS.
Which values does the "mode" state has when your VIS is freezing? The correct value or something weird?

**Comment by hadavid2482** [comment]
It has the correct value.

**Comment by Black-Thunder** [comment]
Then it is definitely no problem from the melcloud adapter and has to be a visualization problem. 😉 
Maybe look for help in the forum or open a bug for the VIS adapter.
