### ISSUE TITLE
Object nextCommunication has "Invalid date" after updating javascript or admin adapter

### ISSUE THREAD

**Issue by jayfizzle** [Black-Thunder/ioBroker.melcloud#128]
**Describe the bug**  
The Object "nextCommunication" has "Invalid date" after updating javascript or admin

**To Reproduce**  
1. Open object "melcloud.0.devices.X.info.nextCommunication"
2. Check state

**Expected behavior**  
date should be displayed correct like object "melcloud.0.devices.X.info.lastCommunication"

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/40118991/122378144-fc82a900-cf65-11eb-8464-ac94ab534d22.png)

**Versions:**  
 - Adapter version: 1.1.4
 - JS-Controller version: 3.3.12
 - Node version: v12.19.0
 - Operating system: raspbian

**Additional context**

**Comment by Black-Thunder** [comment]
That's intended behavior.
The state "nextCommunication" only has a valid value/date when a pending command is outstanding, e.g. some device setting was changed. After the change was received by MELCloud, the state is filled with "null" again and "lastCommunication" is filled accordingly. Objects with type "date" und value "null" are interpreted as "Invalid Date" in the object tree.

**Comment by jayfizzle** [comment]
ok, thanks. So this issue can be closed.
