### ISSUE TITLE
Log warn nach versuchtem Update auf 1.1.5

### ISSUE THREAD

**Issue by Matt77CHE** [Black-Thunder/ioBroker.melcloud#276]
Hallo
Ich habe soeben versucht auf 1.1.5 das Update zu machen;
Im Log sehe ich keine Meldung bezüglich dass das Update nicht durchgeführt worden ist - bei den Instanzen steht jedoch auch nach dem Update noch die 1.1.4 - und bei den Adapter-Updates erscheint es auch immer noch. (keine Ahnung ob das ein Bug im heute geupdateten Controler ist..)

Was aber im Log stand ist der Warn nach dem Update:
" warn | This object will not be created in future versions. Please report this to the developer. "
" warn | Object devices.14778845.reports.getPowerConsumptionReport is invalid: obj.common.min is only allowed on obj.common.type "number" or "mixed", received "boolean" "

Controler: 4.0.4
Node.js: v14.19.0 

Gruss
Matt

**Comment by Black-Thunder** [comment]
Da ist leider was beim Veröffentlichen der v1.1.5 schiefgelaufen. Hab gerade nochmal v1.1.6 nachgeschoben und sollte damit bald als Updates angeboten werden. Damit dürfte das Problem hoffentlich erledigt sein. :wink:

**Comment by Matt77CHE** [comment]
habe es installiert - sieht soweit gut aus !

Danke dir.
