### ISSUE TITLE
Nur für Klimageräte oder auch für andere MelCloud Geräte

### ISSUE THREAD

**Issue by radebold** [Black-Thunder/ioBroker.melcloud#278]
Hallo Zusammen,

ich habe eine Wärempumpe (Heizung) und kann auch über die MelCloud darauf zugreifen.
Nun Habe ich mal den Adapter installiert. Adapter ist grün und es werden mir auch viele Objekte angezeigt aber der größte Teil ist Null oder 0

Kann ich irgendetwas tun, unterstützen ?

Viele Grüße
Thomas

**Comment by Black-Thunder** [comment]
Also grundsätzlich ist der Adapter auf Klimaanlagen ausgelegt und getestet worden. Aber du kannst gerne mal das Loglevel auf Debug stellen und das Log nach Adapterstart hier anhängen. Nur bitte darauf achten, dass du deine sensiblen Informationen vorher aus dem Log entfernst.
Evtl. lässt sich das ja einfach erweitern, aber versprechen kann ich nichts. :wink:

**Comment by radebold** [comment]
[iobroker.2022-02-07.log](https://github.com/Black-Thunder/ioBroker.melcloud/files/8015002/iobroker.2022-02-07.log)

ich hoffe ich habe Alles rausgenommen :-)

**Comment by Black-Thunder** [comment]
Also grundsätzlich sieht die Struktur auf den ersten Blick nicht so viel anders aus wie bei Klimageräten. Von daher könnte das schon mit einigen Anpassungen klappen.

Fraglich wird sicherlich sein, was genau steuerbar ist und ob sich die nötigen Flags dazu unterscheiden. Welche Kommandos sind denn über die Melcloud möglich? Bzw. welche Felder/Funktionen lassen sich steuern? Du kannst auch gerne mal nen Screenshot von den Steuerungsmöglichkeiten der Wärmepumpe unter https://app.melcloud.com/ schicken.

**Comment by radebold** [comment]
mich würde ja zunächst mal die Werte interessieren :-)

Die Bedienung sieht aktuell sehr Oberflächlich aus

![grafik](https://user-images.githubusercontent.com/25064101/152802977-c59adc24-a309-4814-946b-f433ede49b2b.png)
![grafik](https://user-images.githubusercontent.com/25064101/152803495-0ce75ce1-34a8-4f55-b918-b62bc284cb9a.png)
![grafik](https://user-images.githubusercontent.com/25064101/152803623-fd556be4-33d3-4baf-8131-da6573818abb.png)
![grafik](https://user-images.githubusercontent.com/25064101/152803829-db3f0561-298f-44f8-b781-bad5430a7a0c.png)
![grafik](https://user-images.githubusercontent.com/25064101/152803975-8e5841d8-ae2a-49c4-8650-9578477e8ca1.png)

**Comment by Black-Thunder** [comment]
Die musst du händisch installieren, da nicht freigegeben.
Unter 'Adapter' auf das GitHub-Icon (Katze) klicken, evtl. vorher den Expertenmodus aktivieren.  Dort dann auf "VON GITHUB" gehen und im Feld darunter "melcloud" eingeben, dann taucht mein Adapter auf. Damit ziehst du dir den aktuellen Entwicklungsstand von GitHub.

**Comment by Black-Thunder** [comment]
@radebold Hattest du schon Gelegenheit, das bei dir zu testen? 

Zwischenzeitlich hab ich einfach mal auf Verdacht noch weitere Funktionalitäten eingebaut und die Steuermöglichkeiten deutlich erweitert. Wäre super, wenn du dazu Feedback geben könntest, ob und was davon wirklich funktioniert. 😉 
Die [Doku](https://github.com/Black-Thunder/ioBroker.melcloud/blob/master/docs/de/melcloud.md#luft-wasser-w%C3%A4rmepumpen----adapter-version-120-oder-h%C3%B6her-erforderlich) dazu hab ich soweit auch angepasst.

**Comment by radebold** [comment]
@Black-Thunder 

Ich hatte es installiert, vorgestern ist mein iob weggeflogen und ich habe erstmal recoverd :-(

Aber es sieht schon mal ganz gut aus.

![grafik](https://user-images.githubusercontent.com/25064101/153419300-34ea6449-64e3-4ef4-bc27-9008e3b83f45.png)

Vielen Dank für deine super Arbeit. Ich muss gerade erstmal rumspielen. Die Heizung ist auch gerade erst neu :-)

**Comment by Black-Thunder** [comment]
Alles gut, keine Eile. Sieht auf den ersten Blick ja schon mal ganz vielversprechend aus. 👍 

Gib mir einfach Bescheid, wenn du ein bisschen damit rumspielen konntest. Gerade, ob die states unter "control" so funktionieren wie gewünscht.

**Comment by ZoltanBrindza** [comment]
Danke für die Antwort Sollte es auch mit Temperatureinstellung funktionieren?

**Comment by Black-Thunder** [comment]
Ja, jeder State, der beschreibbar ist, lässt sich damit auch entsprechend auf den gewünschten Wert ändern.

**Comment by BonnTech** [comment]
Der Adapter kann auch für Wärmepumpen genutzt werden.
Wir haben alles insoweit getestet. Bisher haben wir die Werte über einen Modbus Adapter ausgelesen.
Darin enthalten sind wirklich alle erdenklichen Werte der Wärmepumpe (Read and Write).
Ob die Werte alle in den Cloud Adapter umgesetzt wurden kann ich nicht sagen, gehe aber davon aus. Nach Aussage MEL kann der Support über den Cloud Adapter auf vieles zugreifen. Wir haben  eine Testwärmepumpe bei uns laufen, ich biete gerne den Zugang an für Tests und bin auch gerne bereit zur Unterstützung. Aktuell bauen wir uns eine VIS zur Visualisierung. Die stellen wir dann gerne zur Verfügung.  Für Viessmann Adapter für eine Heizungsanlage ist diese fast fertig

**Comment by ZoltanBrindza** [comment]
Hi
vielen Dank für Ihre Unterstützung und Bereitschaft, nächsten Monat wird das Gerät installiert, also werde ich sehen, für mich wird das Gerät über Loxone überwacht und gesteuert, daher bin ich sehr gespannt auf das Ergebnis.😀 Ich schätze Ihre Arbeit 👍👍👍und würde gerne Ihre Testgeräte ausprobieren,

**Comment by BonnTech** [comment]
Hallo Zoltan,

kann ich Dir über diesen Weg vertrauliche Daten zusenden?

Ich meine: Zugangsdaten zur MEL Cloud.

Zur Info:
Es sind zwei Wärmepumpen angelegt.

Bitte absolut vertraulich behandeln, eine Anlage ist Kundenanlage (Schnepper)

***@***.***


Zugang funktioniert gut nach ein paar Problemen mit dem JS-Controller Update.
Hab es im IO-Broker implementiert.

Bitte beachten sie, dass die Anlage 32441517 neuste Bauart montiert Anfang des Jahres.
Aktuelle Software und neuer Regler, und neuer WIFI Adapter

Die Anlage 42345971 hat neuen WiFi Adapter aber einen Alten Regler (6Jahre alt). Ggf. gibt es da Probleme
Beides sind Ecodan Wärmepumpen. Diese Anlage ist bei uns im Büro.

Es gibt eine Liste mit Registern und Werten für den zugriff Modbus. Das ist aber keine gute Lösung, da der spezielle Adapter über 500 EUR kostet. Also nichts für Endkunden. Da sind alle Register drin was man aus der Anlage herauslesen kann. Ob diese Liste über den WIFI Adapter gespiegelt ist, weiß ich nicht.

Die Liste gibt’s im Internet ist aber nicht ganz leicht zu finden. Kann ich aber gerne zusenden wenn gewünscht. Wir sind seit 35 Jahren Mitsubishi Partner aber auch wir bekommen nicht viele Informationen. Wenn Du aber etwas benötigst, kann ich gerne Mitarbeiter anfragen.

Wichtig wird zunehmend die Visualisierung der daten, Temperaturen aber auch das SmartGrid Ready. Damit kann man die Wärmepumpe mit dem Wechselrichter koppeln, so das Marketing. Offiziell geht natürlich hier nichts außer mit einem Schaltdarht im Heizungskeller. Wäre eine Challenge das hinzubekommen über die Cloud.

Wenn Du was brauchst, wie gesagt melden wir supporten gerne.
Mit freundlichen Grüßen

Markus Schäfer


[http://www.bonntech.srdenergy.de/wp-content/uploads/2014/04/BonntechHille_neu_transparent.png]

BonnTech Hille GmbH & Co. KG
Siemensstraße 17-19
53121 Bonn
GERMANY
USt.-Nr. DE296701045
HRB 20985 Amtsgericht Bonn

Pers. haftende Gesellschafterin
BonnTech Sustainable GmbH, HRB 20985 Bonn
Geschäftsführer Dipl. Wirt.-Ing. (FH) Markus Schäfer

Tel. +49 228 92124-10
Fax +49 228 92124-31
Cell + 49 175 5225885
www.bonntech.de<http://www.bonntech.de/>
***@***.******@***.***>






Von: Zoltan Brindza ***@***.***>
Gesendet: Montag, 6. Juni 2022 14:56
An: Black-Thunder/ioBroker.melcloud ***@***.***>
Cc: BonnTech ***@***.***>; Comment ***@***.***>
Betreff: Re: [Black-Thunder/ioBroker.melcloud] Nur für Klimageräte oder auch für andere MelCloud Geräte (Issue #278)


Hi
vielen Dank für Ihre Unterstützung und Bereitschaft, nächsten Monat wird das Gerät installiert, also werde ich sehen, für mich wird das Gerät über Loxone überwacht und gesteuert, daher bin ich sehr gespannt auf das Ergebnis.😀 Ich schätze Ihre Arbeit 👍👍👍und würde gerne Ihre Testgeräte ausprobieren,

**Comment by BonnTech** [comment]
Achtung es gibt mehrere Versionen der Hauptplatinen in den Luft-Wasser Wärmepumpen.
Daten können per Modbus ausgelesen werden oder mit dem WiFi Adapter. Daten für eine aktuelle Platine FTC6 (neuste Version) mit Originaldaten einer Wärmepumpe anbei:


PCycleActual                  : 0
ErrorMessages                 :
DeviceType                    : 1
FTCVersion                    : 1301
FTCRevision                   : c1
LastFTCVersion                : 0
LastFTCRevision               :
FTCModel                      : 3
RefridgerentAddress           : 0
DipSwitch1                    : 54
DipSwitch2                    : 160
DipSwitch3                    : 16
DipSwitch4                    : 0
DipSwitch5                    : 38
DipSwitch6                    : 4
HasThermostatZone1            : True
HasThermostatZone2            : True
TemperatureIncrement          : 0.5
DefrostMode                   : 0
HeatPumpFrequency             : 0
MaxSetTemperature             : 55.0
MinSetTemperature             : 25.0
RoomTemperatureZone1          : -39.0
RoomTemperatureZone2          : -39.0
OutdoorTemperature            : 17.0
FlowTemperature               : 37.0
FlowTemperatureZone1          : 42.0
FlowTemperatureZone2          : 25.0
FlowTemperatureBoiler         : 25.0
ReturnTemperature             : 35.5
ReturnTemperatureZone1        : 40.0
ReturnTemperatureZone2        : 25.0
ReturnTemperatureBoiler       : 25.0
BoilerStatus                  : False
BoosterHeater1Status          : False
BoosterHeater2Status          : False
BoosterHeater2PlusStatus      : False
ImmersionHeaterStatus         : False
WaterPump1Status              : False
WaterPump2Status              : False
WaterPump3Status              : False
ValveStatus3Way               : False
ValveStatus2Way               : False
WaterPump4Status              : False
ValveStatus2Way2a             : False
ValveStatus2Way2b             : False
TankWaterTemperature          : 50.5
UnitStatus                    : 0
HeatingFunctionEnabled        : True
ServerTimerEnabled            : False
ThermostatStatusZone1         : False
ThermostatStatusZone2         : False
ThermostatTypeZone1           : 2
ThermostatTypeZone2           : 2
MixingTankWaterTemperature    : 25.0
CondensingTemperature         : 15.06
DemandPercentage              : 100
ConfiguredDemandPercentage    :
HasDemandSideControl          : True
DailyHeatingEnergyConsumed    : 1.04
DailyCoolingEnergyConsumed    : 0.0
DailyHotWaterEnergyConsumed   : 13.81
DailyHeatingEnergyProduced    : 0.09
DailyCoolingEnergyProduced    : 0.0
DailyHotWaterEnergyProduced   : 9.99
EffectiveFlags                : 0
LastEffectiveFlags            : 0
Power                         : True
EcoHotWater                   : False
OperationMode                 : 0
OperationModeZone1            : 2
OperationModeZone2            : 2
SetTemperatureZone1           : 11.0
SetTemperatureZone2           : 20.0
SetTankWaterTemperature       : 51.0
TargetHCTemperatureZone1      : 30.5
TargetHCTemperatureZone2      : 35.0
ForcedHotWaterMode            : False
HolidayMode                   : False
ProhibitHotWater              : False
ProhibitHeatingZone1          : True
ProhibitHeatingZone2          : True
ProhibitCoolingZone1          : False
ProhibitCoolingZone2          : False
ServerTimerDesired            : False
SecondaryZoneHeatCurve        : False
SetHeatFlowTemperatureZone1   : 12.0
SetHeatFlowTemperatureZone2   : 20.0
SetCoolFlowTemperatureZone1   : 20.0
SetCoolFlowTemperatureZone2   : 20.0
DECCReport                    : False
CSVReport1min                 : False
Zone2Master                   : False
DailyEnergyConsumedDate       : 2022-09-09T00:00:00
DailyEnergyProducedDate       : 2022-09-09T00:00:00
CurrentEnergyConsumed         : 0
CurrentEnergyProduced         : 0
CurrentEnergyMode             :
HeatingEnergyConsumedRate1    : 0
HeatingEnergyConsumedRate2    : 0
CoolingEnergyConsumedRate1    : 0
CoolingEnergyConsumedRate2    : 0
HotWaterEnergyConsumedRate1   : 0
HotWaterEnergyConsumedRate2   : 0
HeatingEnergyProducedRate1    : 0
HeatingEnergyProducedRate2    : 0
CoolingEnergyProducedRate1    : 0
CoolingEnergyProducedRate2    : 0
HotWaterEnergyProducedRate1   : 0
HotWaterEnergyProducedRate2   : 0
ErrorCode2Digit               : 0
SpSubDivisionsToWrite         : 0
SpSubDivisionsToRead          : 0
SpState                       : 0
SpSubDivisionsWriteInProgress : 0
SpSubDivisionsReadInProgress  : 0
InitialSettingsData           :
InitialSettingsTimestamp      :
SupportsHourlyEnergyReport    : False
HasZone2                      : False
HasSimplifiedZone2            : False
CanHeat                       : True
CanCool                       : False
HasHotWaterTank               : True
CanSetTankTemperature         : True
CanSetEcoHotWater             : True
HasEnergyConsumedMeter        : True
HasEnergyProducedMeter        : True
CanMeasureEnergyProduced      : False
CanMeasureEnergyConsumed      : False
Zone1InRoomMode               : False
Zone2InRoomMode               : False
Zone1InHeatMode               : True
Zone2InHeatMode               : True
Zone1InCoolMode               : False
Zone2InCoolMode               : False
AllowDualRoomTemperature      : False
IsGeodan                      : False
HasEcoCuteSettings            : False
HasFTC45Settings              : True
HasFTC6Settings               : True
CanEstimateEnergyUsage        : True
CanUseRoomTemperatureCooling  : False
IsFtcModelSupported           : True
MaxTankTemperature            : 60.0
IdleZone1                     : True
IdleZone2                     : True
MinPcycle                     : 1
MaxPcycle                     : 1
MaxOutdoorUnits               : 255
MaxIndoorUnits                : 255
MaxTemperatureControlUnits    : 0
ModelCode                     : 027a
DeviceID                      : 32441517
MacAddress                    : 70:61:be:36:3a:ff
SerialNumber                  : 2140212162
TimeZoneID                    : 119
DiagnosticMode                : 0
DiagnosticEndDate             :
ExpectedCommand               : 1
Owner                         : 480873
DetectedCountry               :
AdaptorType                   : 3
FirmwareDeployment            :
FirmwareUpdateAborted         : False
LinkedDevice                  :
WifiSignalStrength            : -55
WifiAdapterStatus             : NORMAL
Position                      : Unknown
PCycle                        : 2
PCycleConfigured              :
RecordNumMax                  : 1
LastTimeStamp                 : 2022-09-10T12:56:00
ErrorCode                     : 8000
HasError                      : False
LastReset                     : 2022-03-31T19:46:47.788
FlashWrites                   : 4
Scene                         :
TemperatureIncrementOverride  : 0
SSLExpirationDate             : 2037-12-31T00:00:00
SPTimeout                     : 1
Passcode                      :
ServerCommunicationDisabled   : False
ConsecutiveUploadErrors       : 0
DoNotRespondAfter             :
OwnerRoleAccessLevel          : 1
OwnerCountry                  : 85
HideEnergyReport              : False
ExceptionHash                 :
ExceptionDate                 :
ExceptionCount                :
Rate1StartTime                :
Rate2StartTime                :
ProtocolVersion               : 0
UnitVersion                   : 0
FirmwareAppVersion            : 35000
FirmwareWebVersion            : 0
FirmwareWlanVersion           : 0
EffectivePCycle               : 1
MqttFlags                     : 9
HasErrorMessages              : False
Offline                       : False
Units                         : {}

**Comment by Black-Thunder** [comment]
Grundsätzlicher Support für Wärmepumpen besteht seit v1.2.0. Wenn noch Fehler/Probleme/Wünsche diesbezüglich auftreten, bitte neue Issues anlegen. Hier mach ich zu.
