### ISSUE TITLE
Adapter lässt sich nicht installieren

### ISSUE THREAD

**Issue by severendis** [Black-Thunder/ioBroker.melcloud#410]
Ich versuche den Adapter in der Version 1.2.0 (von GitHub) im iOBroker zu installieren. Hatte vorher die Version 1.1.6 drauf. Diese habe ich gelöscht (auch den Ordner in den Objekten), da ich erst dachte, das es an der bestehenden Installation liegt.

Bei Befehl ausführen bleibt ewig der Status:
`$ iobroker url Black-Thunder/ioBroker.melcloud --host iobroker --debug

install Black-Thunder/ioBroker.melcloud

NPM version: 6.14.17

Installing Black-Thunder/ioBroker.melcloud... (System call)`

Wenn ich wieder versuche die 1.1.6 Version die direkt im iOBroker zur Verfügung steht zu installieren, dann geht das ohne Probleme.

Ich habe es sowohl über GitHub als auch direkt über die Adresse versucht. Immer das gleiche.
Was kann das Problem sein?

**Comment by Black-Thunder** [comment]
Also das Problem liegt denk ich weniger am Adapter selbst, denn bei mir lässt sich die 1.2.0 ohne Probleme von Github installieren und auch die automatisierten Tests laufen problemlos durch. Ich vermute eher ein lokales Problem mit deiner Installation.

Welche nodejs-Version verwendest du denn ("nodejs -v")? "NPM version: 6.14.17" klingt eher nach einer älteren Version. Eventuell auch mal nach folgender Anleitung prüfen und ggf. updaten: https://forum.iobroker.net/topic/44566/how-to-node-js-iobroker-richtig-updaten-2021-22-edition

**Comment by severendis** [comment]
Danke für den Tip. Nun habe ich das System mal auf den aktuellen Stand gebracht (denke ich).
Node.js: v16.17.1(16.18.0)
NPM: 8.15.0(8.19.2)

Jetzt kann ich es von GitHub installieren und es wird mir in den Adaptern auch angezeigt:
Verfügbare Version:
1.1.6
Installierte Version:
1.2.0

In den Instanzen ist der Adapter aber nicht zu sehen. Wo könnte ich hier noch zur Fehlersuche ansetzen?
Ich habe testweise wieder den 1.1.6 probiert und der geht ohne Probleme.

Danke !

**Comment by Black-Thunder** [comment]
Um eine Instanz des Adapters zu bekommen, musst du unter "Adapter" neben MELCloud auf das "+" klicken:

![image](https://user-images.githubusercontent.com/972581/195730249-0e982646-637b-48c6-a234-0338fa2740e7.png)

Danach siehst du ihn unter "Instanzen".

**Comment by severendis** [comment]
Oh man - das vergesse ich immer wieder, da ich das zu selten mache. hat sofort funktioniert. Danke!

PS: Frage noch. Es gibt einige Datenpunkte zur Energie (kWh) in dem Adapter, die bei mir alle nur 0 anzeigen. Gibt das die Wärmepumpe nicht her, oder kann man da an dem Adapter vielleicht noch was rausholen.

**Comment by Black-Thunder** [comment]
> PS: Frage noch. Es gibt einige Datenpunkte zur Energie (kWh) in dem Adapter, die bei mir alle nur 0 anzeigen. Gibt das die Wärmepumpe nicht her, oder kann man da an dem Adapter vielleicht noch was rausholen.

Puh, letzteres ist durchaus möglich. 😉 
Zu Wärmepumpen gab es bisher kaum Feedback, von daher ist das alles noch nicht so wirklich verifiziert und selbst hab ich dazu keine Möglichkeit. Aber erstelle dazu bitte einen neuen Issue mit den betroffenen Datenpunkten und einem Log des Adapters (am besten auf Logstufe "Alles"/"silly" und ohne deine persönlichen Daten). Dann kann ich mir das noch anschauen.

Hier mache ich zu, ist ja gelöst. 😉
