### ISSUE TITLE
enable/disable timer

### ISSUE THREAD

**Issue by floriankra88** [Black-Thunder/ioBroker.melcloud#475]
is it possible to add enable/disable timer in controls?

**Comment by Black-Thunder** [comment]
Do you mean a global toggle just for switching the timer on and off per device or adding the whole functionality of defining timers? I think the first one shouldn't be too hard to implement, but I'll have to look into it.

**Comment by Black-Thunder** [comment]
@floriankra88 I've just uploaded a few changes to GitHub which includes the functionality to toggle the timer state on/off. To use this there is a new state under "melcloud.X.devices.Y.control.timerToggle"". Setting true enables, setting false disables the timer for the device.

Please test this new version (install from GitHub) if there are any errors or problems. If so, please provide a debug log.

**Comment by floriankra88** [comment]
i have installed and tested it, works greate :)

thx man

**Comment by Black-Thunder** [comment]
Great. 😃 
This is now in included in v1.3.0
