### ISSUE TITLE
Befehl zum Starten der Warmwasseraufbereitung

### ISSUE THREAD

**Issue by OssiSester** [Black-Thunder/ioBroker.melcloud#480]
Das wäre ein Super Feature, dass man leider derzeit nicht über die MelCloude machen kann.

Super wäre es, über einen Befehl die Anlage aufzufordern, jetzt die Warmwasseraufbereitung zu starten.
Somit könnte man eine Art SG Ready Funktion nachstellen.

ZB es ist genug Solarenergie verfügbar. Über SetTankWaterTemperatur könnte man diese auf ZB 55 einstellen und über den Befehl die Anlage dazu bringen, JETZT auf diese Temperatur aufzuheizen.

Danke euch

**Comment by Black-Thunder** [comment]
Verstehe ich das richtig, dass es diese Steueroption (also Start der Warmwasseraufbereitung) über Melcloud gar nicht gibt? Dann kann ich da leider nichts machen, da der Adapter im Prinzip nur die App imitiert und daher nur dieselben Befehle wie dort absetzen kann.

**Comment by OssiSester** [comment]
Ah, OK verstehe.

Danke dennoch
