### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by McGlenWin** [Black-Thunder/ioBroker.melcloud#505]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  

Der Adapter startet nicht mehr bleibt auf rot.
Habe ihn dann auf die neuste Version upgedatet, aber auch kein Erfolg.
Habe auch mal das Passwort gelöscht und neu eingegeben. Im Internet und über App kann ich mich noch in der Melcloud anmelden....
Lief über Monate ohne Problem.

Log:

<html>
<body>

melcloud.0 | 2023-05-10 18:12:38.787 | error | Error: unable to verify the first certificate
-- | -- | -- | --
melcloud.0 | 2023-05-10 18:12:38.787 | error | There was a problem sending login to: https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin
melcloud.0 | 2023-05-10 18:12:38.578 | info | Connecting initially to MELCloud and retrieving data...
melcloud.0 | 2023-05-10 18:12:38.357 | info | starting. Version 1.3.3 in /opt/iobroker/node_modules/iobroker.melcloud, node: v14.20.1, js-controller: 4.0.23
melcloud.0 | 2023-05-10 18:12:33.425 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
melcloud.0 | 2023-05-10 18:12:33.422 | info | terminating
melcloud.0 | 2023-05-10 18:12:33.420 | info | onUnload(): Cleaned everything up...
melcloud.0 | 2023-05-10 18:12:33.415 | info | Got terminate signal TERMINATE_YOURSELF
melcloud.0 | 2023-05-10 18:12:14.548 | error | Error: MELCloud password empty! Check settings.
melcloud.0 | 2023-05-10 18:12:14.438 | info | starting. Version 1.3.3 in /opt/iobroker/node_modules/iobroker.melcloud, node: v14.20.1, js-controller: 4.0.23
melcloud.0 | 2023-05-10 18:12:09.523 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
melcloud.0 | 2023-05-10 18:12:09.520 | info | terminating
melcloud.0 | 2023-05-10 18:12:09.519 | info | onUnload(): Cleaned everything up...
melcloud.0 | 2023-05-10 18:12:09.516 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>

**Comment by Black-Thunder** [comment]
`melcloud.0	2023-05-10 18:12:14.548	error	Error: MELCloud password empty! Check settings.`

Laut Log ist kein Passwort in den Instanzeinstellungen hinterlegt. Versuch es bitte nochmal zu löschen, dann speichern und danach neu eingeben und wieder speichern. Wenn es immer noch nicht klappt, bitte die Logstufe des Adapters auf "Debug" stellen und ein neues Log posten.

**Comment by Black-Thunder** [comment]
Und das eigentliche Problem bzgl. "Error: unable to verify the first certificate" kann ich bei mir auch nachvollziehen. Ich vermute, da hat Mitsubishi etwas an der Anmeldung verändert. Schau ich mir dann an.

**Comment by Black-Thunder** [comment]
Das Problem hier scheint zu sein, dass die Zertifikatskette, die von der Melcloud geliefert wird, nicht mehr korrekt bzw. vollständig ist und daher der Aufruf scheitert.

Ich habe gerade in der dev-Branch (https://github.com/Black-Thunder/ioBroker.melcloud/tree/dev) eine Umgehung eingebaut, mit der es vorerst wieder funktionieren sollte. Ist aber nichts auf Dauer und muss ich mir nochmal genauer anschauen. Wenn du magst, gerne mal aus dem dev-Branch installieren und berichten.

**Comment by Black-Thunder** [comment]
Nochmal ich 😉 
Habe gerade noch einige Anpassungen in den dev-Branch hochgeladen, die das Problem mit den Zertifikaten lösen sollten und dabei keine Sicherheitslücke einbauen. Bitte mit dieser Version testen und berichten, ob es bei dir wieder funktioniert. Dann würde ich kurzfristig eine neue Version freigeben.

**Comment by McGlenWin** [comment]
Habe ich noch nicht gemacht.
Ich nehme an, dass ich bei Adapter auf den Expertenmodus gehen muss und dann eine benutzerdefinierte URL eingeben muss.
Ich nehme an dies ist eine URL aus dem dev Bereich des Repository, aber welche?
Habe ausprobiert...
$ iobroker url https://github.com/Black-Thunder/ioBroker.melcloud/tree/dev/.github --host pi04 --debug

install Black-Thunder/ioBroker.melcloud#dev/.github

NPM version: 6.14.17

Installing Black-Thunder/ioBroker.melcloud#dev/.github... (System call)

npm ERR! code 1

npm ERR! error: Pfadspezifikation 'dev/.github' stimmt mit keinen git-bekannten Dateien überein.npm ERR!

npm ERR! /home/iobroker/.npm/_logs/2023-05-11T08_33_22_844Z-debug.log

upload [13] melcloud.admin /opt/iobroker/node_modules/iobroker.melcloud/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [12] melcloud.admin /opt/iobroker/node_modules/iobroker.melcloud/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [8] melcloud.admin /opt/iobroker/node_modules/iobroker.melcloud/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [6] melcloud.admin /opt/iobroker/node_modules/iobroker.melcloud/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [0] melcloud.admin /opt/iobroker/node_modules/iobroker.melcloud/admin/words.js words.js application/javascript

Update "system.adapter.melcloud.0"

Process exited with code 0

**Comment by Black-Thunder** [comment]
Alles soweit richtig, als URL aber bitte nur "https://github.com/Black-Thunder/ioBroker.melcloud/tree/dev" verwenden.

**Comment by McGlenWin** [comment]
Super, bei mir läuft es auch wieder, danke für den super schnellen und kompetenten Support

**Comment by Black-Thunder** [comment]
Perfekt, danke euch beiden für die Rückmeldung. Die Änderungen gebe ich gleich als v1.3.4 frei (zunächst im latest und bald dann auch im stable).
