### ISSUE TITLE
Memory Leak: RAM consumption increases over time

### ISSUE THREAD

**Issue by christofkac** [Black-Thunder/ioBroker.melcloud#542]
**Describe the bug**  
I observed problems with RAM availability on my ioBroker VM instance and investigate the consumption of all adapters using Telegraf and Grafana.
One of the main problematic adapters is MelCloud:
![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/33951830/b186639d-54a0-4deb-9ed7-f6c29f1cdbb8)
Within 2 days, the consumption went up from 2% (of 5 GByte RAM) to 10%.
At the beginning of the graph, I rebootet my VM to have a clean start, therefore you see the drop.
![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/33951830/7c90ca46-ba00-430c-b2b2-1337e6bbeb40)
In my setup, I poll the information for 2 A/C devices from the Melcloud.

**To Reproduce**  
Start the adapter and wait. Observe the RAM consumption

**Expected behavior**  
Stable memory consumption 

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 1.34
 - JS-Controller version: 4.0.24
 - Node version: v18.17.0
 - Operating system: Debian VM

Let me know if any further information is required. I'm willing to support the debugging if this helps

**Comment by Black-Thunder** [comment]
Yes, I've also noticed this recently. Seems to have started with v1.3.4 where the certificilate issue has been fixed. But since I'm on vacation right now, investigation of this problem has to wait a little longer 😉

**Comment by christofkac** [comment]
Thanks for the response - as it is not urgent, I can wait ;-)

**Comment by Black-Thunder** [comment]
One quick thing you might try is to go back to v1.3.3 and see if the certificilate issue is still there. Maybe Mitsubishi fixed that on their end in the meantime and that version works again.

**Comment by SKB-CGN** [comment]
I can confirm this. When starting the adapter, it has around 60MB.

After some time, i am at 220MB.

**Comment by Black-Thunder** [comment]
@SKB-CGN Please try v1.3.3. According to other projects the certificate issue should have bee

**Comment by Black-Thunder** [comment]
@SKB-CGN @christofkac Just a quick note, v1.3.3 works fine again without certificate issues. As a workaround please downgrade to this version as this has no memory leak. Next week I'll release a new version.

**Comment by Black-Thunder** [comment]
@SKB-CGN @christofkac I've just released v1.3.5 (via latest/beta repository). Please try that version and give feedback if the memory leak is solved.

**Comment by christofkac** [comment]
Adapter installed - will monitor memory consumption over the next days.
Thanks for the fast update.
And BTW: 1.3.3 worked fine also on my side

**Comment by christofkac** [comment]
So, I can confirm that the memory leak is gone:
![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/33951830/dfd55b38-d701-4515-b91e-1e57812a5148)

**Comment by Black-Thunder** [comment]
Great, thanks for the confirmation, memory consumption is also fine again on my system now.

v1.3.5 will move to the stable repo then.
