### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by Chris9463773** [Black-Thunder/ioBroker.melcloud#678]
Unfortunately I still have the problem that the connection to MelCloud cannot be established.
I paused the adapter for 3 days now and started it again this evening.
Unfortunately, the familiar error message came immediately
So the adapter couldn't connect to the cloud at all.
I can access the cloud without any problems via https://app.melcloud.com/

What could be the reason?
![Fehlermeldung MelCloud](https://github.com/Black-Thunder/ioBroker.melcloud/assets/156612096/74595e1c-4f1e-486e-bcf4-a6be67b6d417)

**Comment by Black-Thunder** [comment]
Really strange, it should definitely work if you can login to the web interface.
Please attach a debug log, maybe there's more information in it why it fails.

Otherwise you could grant me temporary guest access to your account so I can debug myself what's wrong there. But that's up to you if you trust me that much 😉

**Comment by Chris9463773** [comment]
Unfortunately, I'm quite a beginner.
What is a debug log?
And which access do you mean? To MelCloud?

**Comment by Black-Thunder** [comment]
>What is a debug log?

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/972581/cd769386-daa4-4616-b8e3-cf89e0834bbd)

>And which access do you mean? To MelCloud?

Yes, in the web interface there is an setting to grant guest access:

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/972581/13273a0f-861a-4689-91cd-79f399fa7c4f)

**Comment by Chris9463773** [comment]
![Fehlermeldung MelCloud](https://github.com/Black-Thunder/ioBroker.melcloud/assets/156612096/bbfc36a1-67a9-4cff-b170-272723ac7d56)

OK... which EMail-Adress should i use for Gastzugang ;) ?

**Comment by Black-Thunder** [comment]
Thanks for the log, sadly no further information.

Use "glwars@aol.de" please

**Comment by Chris9463773** [comment]
guest access is set up.
I hope you can find something.

**Comment by Black-Thunder** [comment]
Thanks, got it. Will take a look at it later.

**Comment by Black-Thunder** [comment]
Hmm... I've just tried it with that guest account and the connection works without any problems. So I don't really have an idea why your main account is still being blocked.
You could try and give yourself "guest" access with full rights for an secondary mail address and use that account for the adapter.

**Comment by Chris9463773** [comment]
strange...it works now with guest access. For whatever reason.
But I will also test it with normal access from time to time.
Thanks for the help

**Comment by Black-Thunder** [comment]
No problem, glad you found a workaround.

**Comment by Chris9463773** [comment]
New problem.
After the connection has been successfully established, a scheduled restart will be initiated a few seconds later.
This happens over and over again. until the cloud is blocked again.
![Fehlermeldung MelCloud](https://github.com/Black-Thunder/ioBroker.melcloud/assets/156612096/ed8b1a74-8853-4c83-b7c8-de111f94ccc8)

**Comment by Black-Thunder** [comment]
Kann es sein, dass du in den Instanzeinstellungen selbst einen (sehr häufigen) automatischen Neustart eingetragen hast?

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/972581/bc253a8b-8ab1-415a-93a4-13e3b4ab01d8)

Also hier mal kontrollieren und, falls ja, den geplanten Neustart am besten ganz rausnehmen:

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/972581/1c8e018e-e7a5-4313-9b93-e937235be372)

**Comment by Chris9463773** [comment]
Da war nichts aktiviert.
Ich habe aber dann mal einen Intervall ausgewählt und wieder gelöscht... jetzt ist seit 15 Minuten Ruhe.
Heute Nachmittag mal schauen, was bis dahin passiert.

**Comment by Black-Thunder** [comment]
Wenn beim Start im Log nicht mehr die obige Zeile ("Schedule restart:...") auftaucht, ist das Problem sicherlich gelöst.

Ich würde dir aber grundsätzlich mal empfehlen, deinen js-controller bei Gelegenheit auf die aktuelle Version 5.x zu aktualisieren.

**Comment by Chris9463773** [comment]
Bisher funktioniert alles... Danke erstmal

js-controller update... da muss ich mal schauem, wie das funktioniert ;)

**Comment by Black-Thunder** [comment]
Freut mich, wenn es bisher wieder läuft 👍 

Für das Update des js-controllers am besten nach der [offiziellen Anleitung](https://forum.iobroker.net/topic/68290/js-controller-5-0-x-jetzt-f%C3%BCr-alle-user-im-stable) vorgehen und die dortigen Hinweise beachten, dann kann nichts schief gehen.
