### ISSUE TITLE
Info. The WIFI module can't connect to the MelCloud server. (It's not the Adapter issue)

### ISSUE THREAD

**Issue by vvfrwl** [Black-Thunder/ioBroker.melcloud#704]
If anybody has a MelCloud communication problem:
1. That is not the adapter problem.
2.  
"It's a global issue. The WIFI module can't connect to the server. So it just fails.

The server returns 503 Service Unavailable: Back-end server is at capacity

So don't waste your time resetting the wifi and like that. Just waste of time.

I also got this response after contacting the technical support

As you may have noticed, we are currently facing a communication problem regarding our WiFi interfaces. I would like to assure you that our technical team is fully committed to resolving this issue.

We implement all necessary resources to ensure that these inconveniences are resolved as quickly as possible. Our goal is to ensure the reliability and performance of our services, and rest assured that we are working diligently to restore the situation to normal."

"Workaround:
If you manage your own DNS server, you can get online again, setting the host "production.receiver.melcloud.com" to resolve to the IPaddress: 52.215.226.151"

From:
[www.reddit.com](https://www.reddit.com/r/mitsubishi/comments/1c7td2g/melcloud_issues_since_yesterday_anyone_else/)

**Comment by Black-Thunder** [comment]
Finally seems to be up and running again. So this DNS workaround is no longer needed at the moment.
