### ISSUE TITLE
Solltemperatur lässt sich nicht schreiben

### ISSUE THREAD

**Issue by FranzKillig** [Black-Thunder/ioBroker.melcloud#749]
Hallo Zusammen,

ich steuere meine Klimaanlage (Multisplit 1x Aussengerät, 6 Innengeräte) per PV-Überschussteuerung.
Beim Schreiben der Solltemperatur bekomme ich folgende Fehlermeldung:

melcloud.0 | 2024-07-10 16:06:21.219 | error | Unsupported ATA operation mode: '24' - Please report this to the developer!
melcloud.0 | 2024-07-10 15:55:47.169 | error | Unsupported ATA operation mode: '24' - Please report this to the developer!
melcloud.0 | 2024-07-10 15:40:43.793 | error | Unsupported ATA operation mode: '24' - Please report this to the developer!
melcloud.0 | 2024-07-10 15:30:41.499 | error | Unsupported ATA operation mode: '24' - Please report this to the developer!

Ich schreibe den Wert mit einem Blockly-Script:

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/70587675/b805c49a-61d6-4fc8-90e5-c9118bb184ca)

Gruß
Franz

**Comment by Black-Thunder** [comment]
Hier scheint sich ein Fehler in deinem Blockly eingeschlichen zu haben 😉 

![image](https://github.com/Black-Thunder/ioBroker.melcloud/assets/972581/2c18263c-1e7e-48bc-80e3-0b7f8e9800af)

**Comment by FranzKillig** [comment]
Peinlich! Danke für den Hinweis 🫣
