### ISSUE TITLE
Error: connect ETIMEDOUT 52.211.141.227:443

### ISSUE THREAD

**Issue by FranzKillig** [Black-Thunder/ioBroker.melcloud#771]
Hallo Zusammen,

seit einigen Tagen habe ich immer wieder folgende Fehlermeldungen:

<html>
<body>

melcloud.0 | 2024-08-24 11:10:02.435 | warn | Connection to MELCloud lost - reconnecting (try 1 of 3)

melcloud.0 | 2024-08-24 11:02:10.020 | error | Error: connect ETIMEDOUT 52.211.141.227:443

melcloud.0 | 2024-08-24 11:02:10.019 | error | There was a problem getting devices from: https://app.melcloud.com/Mitsubishi.Wifi.Client/User/ListDevices

 - Adapter version: 1.4.1
 - JS-Controller version: 6.0.9
 - Node version: 18.20.4
 - Operating system: linux

**Comment by Black-Thunder** [comment]
Diese Meldung besagt im Prinzip nur, dass es Verbindungsprobleme zum Melcloud-Server gibt bzw. der Server nicht erreicht werden konnte (Timeout). Die genannte IP gehört zu Mitsubishi:

![image](https://github.com/user-attachments/assets/c327979f-0576-471a-bd82-45d7794feee6)

Das heißt entweder hat dein Gerät Verbindungsprobleme im Heimnetz (schwaches WLAN etc.), deine Internetverbindung war zu diesem Zeitpunkt unterbrochen oder der Mitsubishi-Server hatte Störungen/Ausfälle. Selbst konnte ich in letzter Zeit solche Ausfälle nicht beobachten, von daher tippe ich auf ein lokales Problem bei dir.

Auf jeden Fall nichts, was ein Problem beim Adapter selbst darstellt. Daher kann ich da nichts machen und schließe hier. :wink:
