### ISSUE TITLE
[BUG] fehlende Datenpunkte 

### ISSUE THREAD

**Issue by arctan89** [Black-Thunder/ioBroker.melcloud#839]
### Bug Description

Hallo,

ich frage eine Mitsubishi LW-Wärmepumpe ab. Leider fehlen mir die folgenden Datenpunkte:
"melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHotWater"
"melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHeat"

Wenn ich mir über "melcloud.0.devices.41808410.reports.getPowerConsumptionReport" die Daten ziehen will kommt folgende Meldung im Log.

![image](https://github.com/user-attachments/assets/eeb70032-110d-4ea1-9352-167db50be523)

Ich habe bereits den Adapter gestoppt, alle Datenpunkte gelöscht und neu gestartet.  Auch hab ich mal ein Downgrade bis Version 1.4.0 versucht. Leider hat das nichts gebracht.

Mach ich was falsch? Oder ist das ein Bug? :)

### Steps to Reproduce

Datumseingabe bei:

melcloud.0.devices.41808410.reports.startDate
melcloud.0.devices.41808410.reports.endDate

Button-Aktivierung:
melcloud.0.devices.41808410.reports.getPowerConsumptionReport

### Expected Behavior

Ausgabe der Daten zu den Objekten:

"melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHotWater"
"melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHeat"

### Debug Log

melcloud.0 | 2024-12-11 14:47:18.020 | warn | State "melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHotWater" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
melcloud.0 | 2024-12-11 14:47:17.948 | warn | State "melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHeat" has no existing object, this might lead to an error in future versions

### Adapter Version

2.0.4

### JS-Controller Version

7.0.3

### Node.js Version

20.18.1

### Operating System

Linux LXLE

**Comment by Black-Thunder** [comment]
Das sollte vermutlich nicht so sein 😉
Aber dazu bräuchte ich bitte ein vollständiges Debug-Log, wenn du den Abruf durchführst.

**Comment by arctan89** [comment]
Ach sorry, ist mein erster gemeldeter Bug, wusste nicht, dass man die Log-Stufen noch ändern kann.

Ich hoffe so passt das? :D

```

melcloud.0 | 2024-12-11 16:29:51.509 | debug | Updated report data for device 41808410 (Wärmepumpe)
melcloud.0 | 2024-12-11 16:29:51.399 | warn | State "melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHotWater" has no existing object, this might lead to an error in future versions
melcloud.0 | 2024-12-11 16:29:51.333 | warn | State "melcloud.0.devices.41808410.reports.lastReportData.totalPowerProductionHeat" has no existing object, this might lead to an error in future versions
melcloud.0 | 2024-12-11 16:29:51.278 | debug | Response from cloud: {"HotWater":[0.84],"InternalTemperature1":null,"InternalTemperature2":null,"ExternalTemperature":null,"Cooling":[0],"Heating":[4.53],"CoP":[4.476722532588454],"MissingSampleQuarter":[null,null,null,null],"MissingSampleMonth":[null,null,null,null,null,null,null,null,null,null,null,null],"ProducedHotWater":[1.69],"ProducedCooling":[0],"ProducedHeating":[22.35],"TotalHeatingConsumed":4.53,"TotalCoolingConsumed":0,"TotalHotWaterConsumed":0.84,"TotalHeatingProduced":22.35,"TotalCoolingProduced":0,"TotalHotWaterProduced":1.69,"AverageInternalTemperature":0,"AverageExternalTemperature":0,"Status":0,"LabelType":1,"TempLabels":null,"Labels":[9],"HasZone2":false,"CurrencySymbol":"kWh","FromDate":"2024-12-09T00:00:00","ToDate":"2024-12-09T00:00:00","DeviceName":"Wärmepumpe","BuildingAddress":null,"BuildingCity":null,"BuildingCountry":null,"CustomerName":null,"costs":null,"TotalMinutes":0,"MissingMinutes":-1440}
melcloud.0 | 2024-12-11 16:29:51.277 | debug | Received response from: https://app.melcloud.com/Mitsubishi.Wifi.Client/EnergyCost/Report (status code: 200 - OK)
melcloud.0 | 2024-12-11 16:29:51.107 | debug | Getting power consumption report for 41808410 (Wärmepumpe)
melcloud.0 | 2024-12-11 16:29:51.105 | debug | Processing command 'getPowerConsumptionReport' with value 'true' for device object with id 41808410 (Wärmepumpe)...
melcloud.0 | 2024-12-11 16:29:51.103 | debug | Trying to get device object with id 41808410...
```

**Comment by Black-Thunder** [comment]
Kein Problem. Mit dem Log kann ich schon mal mehr anfangen. Ich habe auf Github (https://github.com/Black-Thunder/ioBroker.melcloud/tree/dev) gerade auf Verdacht mal eine potentielle Fehlerbehebung eingebaut.

Könntet du bitte die Version installieren und prüfen, ob es damit geht? Dazu im Admin den Expertenmodus aktivieren, unter "Adapter" auf das Katzensymbol klicken und dann bei "Benutzerdefiniert" die URL von oben eingeben.

![image](https://github.com/user-attachments/assets/4b2ce287-6fd3-44fb-807a-8004b41f538c)

**Comment by arctan89** [comment]
Bestens! Beide States sind jetzt vorhanden und werden mit Daten gefüllt.

Danke dir!

**Comment by Black-Thunder** [comment]
Wunderbar, danke dir für die schnelle Rückmeldung. Du bist offensichtlich der Erste, der diese Funktionalität benutzt. Das hat bisher nie korrekt funktioniert. 😆 

Die Fehlerbehebung wird demnächst als v2.0.5 auf den offiziellen Wegen erscheinen. Bis dahin kannst du problemlos den Entwicklungsstand verwenden.
